#!/usr/bin/env python

# Copyright (c) 2016, Michal Szymaniak
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import print_function
import sys
from time import sleep, time
import psutil
import argparse


pids  = list()
procs = dict()

attrs = None
env   = None

formatStr = '{time:.3f}: {pid:6}  {cmd}'

startTime = time()


def printError(*msg):
	print("error: ", *msg, file=sys.stderr)


def printVals(names, vals, prefix=''):
	for name in names:
		if name in vals:
			val = vals[name]
			if val != None:
				if type(val) == str:
					val = '\'' + val + '\''
				print('    {:<12} {}'.format(prefix+name+':', val))


def printProc(proc, cmdline):
	try:
		timestamp = time() - startTime
		procInfo = proc.as_dict(['name', 'exe', 'ppid', 'cwd', 'username'])
		print(formatStr.format( \
				time = timestamp, \
				pid = proc.pid, \
				cmd = ' '.join(cmdline), \
				name = procInfo['name'], \
				exe = procInfo['exe'], \
				ppid = procInfo['ppid'], \
				cwd = procInfo['cwd'], \
				username = procInfo['username'] ))
	except KeyError as ex:
		printError('unknown format key "' + ex.args[0] + '"')
		sys.exit(1)
	except psutil.AccessDenied:
		pass

	try:
		if attrs != None:
			printVals(attrs, proc.as_dict(attrs))
		if env != None:
			printVals(env, proc.environ(), prefix='$')
	except AttributeError as ex:
		printError(ex.args[0])
		sys.exit(1)
	except psutil.AccessDenied:
		pass

		try:
			vals = proc.environ()
		except psutil.AccessDenied:
			pass

	if (attrs != None) or (env != None):
		print('')


def updateProc(proc):
	try:
		cmdline = proc.cmdline()
		if (proc.pid not in procs) or (cmdline != procs[proc.pid]):
			printProc(proc, cmdline)
		procs[proc.pid] = cmdline

		childs = proc.children(recursive=True)
		for child in childs:
			updateProc(child)

	except (psutil.NoSuchProcess, psutil.AccessDenied) as ex:
		if ex.pid in procs:
			del procs[ex.pid]


def update():
	pidsToRemove = list()

	for pid in pids:
		try:
			proc = psutil.Process(pid)
			updateProc(proc)
		except psutil.NoSuchProcess:
			pidsToRemove.append(pid)
			if pid in procs:
				del procs[pid]

	for pid in pidsToRemove:
		try:
			pids.remove(pid)
		except ValueError:
			pass

	# remove child processes that has terminated
	pidsToRemove = list()

	for pid in procs:
		if not psutil.pid_exists(pid):
			pidsToRemove.append(pid)

	for pid in pidsToRemove:
		try:
			del procs[pid]
			pids.remove(pid)
		except ValueError:
			pass


if __name__ == "__main__":
	parser = argparse.ArgumentParser()

	parser.add_argument('PID', type=int, nargs='+',
			help='processes to peek at')

	parser.add_argument('-n', '--interval', type=float, default=0.2,
			help='update interval in seconds, default is 0.2')

	parser.add_argument('-q', '--quick', action='store_true',
			help='run without delay between scans')

	parser.add_argument('-s', '--single', action='store_true',
			help='single pass, scan process tree once and exit');

	parser.add_argument('-a', '--attrs', nargs='+',
			help='extra attributes to read, available fields are: ppid, ' + \
					'name, exe, cmdline, environ, create_time, status, ' + \
					'cwd, username, uids, gids, terminal, nice, ionice, ' + \
					'rlimit, io_counters, num_ctx_switches, num_fds, ' + \
					'num_handles, num_threads, threads, cpu_times, ' + \
					'cpu_percent, cpu_affinity, memory_info, ' + \
					'memory_full_info, memory_percent, memory_maps, ' + \
					'open_files, connections, is_running')

	parser.add_argument('-e', '--env', nargs='+',
			help=' environment variables to read')

	parser.add_argument('-f', '--format', type=str, default=formatStr,
			help='output format string, available fields are: time, ' + \
					'pid, cmd, name, exe, ppid, cwd, username; default is "' + \
					formatStr + '"')

	args = parser.parse_args()

	pids = args.PID
	interval = args.interval
	if args.quick:
		interval = 0

	attrs = args.attrs
	env = args.env
	formatStr = args.format
	singlePass = args.single

	try:
		while True:
			update()

			if singlePass:
				break

			if not pids and not procs:
				break

			if interval > 0:
				sleep(interval)

	except KeyboardInterrupt:
		pass

